### PR TITLE
Elaborated little on the code

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
Hi Marcus!

Elaborated a little on the code you made.
What do you think about these changes?

Also for the future when you want to update your local work use `git rebase upstream/master` instead so we get a clean history. https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa

### CODE REVIEW

**Review by mstormi — APPROVED** [review]

**Comment by mstormi** [comment]
Didn't see this yesterday so it got me a little by surprise
I unintentionally approved those changes of yours but I don't understand them. Will try reverting.
Sorry but yesterday was a really bad day for me, I'm distracted.

**Review by mstormi — COMMENTED** [review]
1) you removed  check_zram_mounts() but have not put it anywhere else, how is checking supposed to take place then ?

2) Why do you think we need to reboot ?

3) why can't we check in docker ?
That used to work in https://travis-ci.com/mstormi/openhabian/builds/120197835

**Comment by EliasGabrielsson** [comment]
1. As I understood the documentation the mounts can be checked using the provided `zramctl` tool.
I did however not manage to get it working in docker.

2. The install `script.sh` wants the machine to be rebooted after installation. 
Maybe not needed or the state can be achived in another way?

3. Are you sure it is working, does the mounts show up in `zramctl`?
You also need to rewrite your test to be of destructive kind.

Besides, this line also needs to be removed:
```
echo "ZRAM not installed - test successful."
```
Use the `skip` functionality of bats-core instead.
See the comments in original PR.

**Comment by EliasGabrielsson** [comment]
I comment out the `zramctl` as I didn't got it working.
See this code as WIP, was easier then comment in original PR.

**Comment by EliasGabrielsson** [comment]
Also you are in "control" for this PR. It's your repo.
i.e I can't merge it and such

**Comment by mstormi** [comment]
on 1)  yes we could also use zramctl but standard df as used in check_zram_mounts() is also fine.
So we actually do not (have to) use zramctl.

on 2) yes it asks to reboot but in fact start/stop works without rebooting so I don't do (we will of course recommend that to users at the end of installation but we don't need to for our testing)

on 3) I'll retry running inside docker with/without using zramctl

**Comment by EliasGabrielsson** [comment]
I don't mind using `chech_zram_mounts()` just make sure that it's in parity with zramctl.
When you feel ready for a "final" review squash together the commits and rebase on top of master.
Looking forward to get this feature onboard, it just need to be solid. 👍

**Comment by mstormi** [comment]
I squashed and finalized code in my [PR #576. ](https://github.com/openhab/openhabian/pull/576)
https://travis-ci.com/mstormi/openhabian/builds/120515410 is the build log of that, see line 534f report successful testing

**Pull request closed without merging**
